.TH "IZULU" "1" "December 02, 2009" "Malte Paskuda" ""
.SH "NAME"
izulu
.SH "SYNOPSIS"
Set the wallpaper according to the weather

.SH "DESCRIPTION"
This manual page documents briefly the
.B izulu
command.
.PP 
\fBizulu\fP is a tool to change the wallpaper according to the weather. Therefore it reads the Dark Sky Forecast API.
.SH "OPTIONS"
.TP 
.B \-c "city"
Set the city with the relevant weather, e.g Berlin.
.TP 
.B \-l "lat:lon"
Set the current position as latitude and longitude coordinates.
.TP 
.BI \-d
Enable daemon\-mode, check the weather every 60 minutes.
.TP 
.B \-i "interval"
Specify a custom check\-interval when in daemon\-mode, e.g. 900 (seconds, also the minimum).
.TP 
.BI \-n
Activate night\-mode, different images will be used at night.
.TP 
.BI \-p
Show the forecast in small preview\-icons.
.TP 
.BI \-r
Choose the wallpaper randomly. Uses the directories named in the config, if none is set it falls back to Flickr.
.TP 
.BI \-t 
Show the temperature
.TP 
.TP 
The command to change the wallpaper, the directories for the random\-mode, the WOEID and the city to check the weather by default may be changed in the config.
.SH "FILES"
It uses a directory .izulu in home directory and /usr/share/izulu. To override the used images, save them in .izulu in the homedirectory with the name gen_sun, gen_cloud, gen_rain, gen_snow or gen_misc, which are also the images used if no specific image exists.
To use further distinct images, save them as:

sun: clear

clouds: partly_cloudy, cloudy

rain: rain, hail

snow: sleet, snow

windy: wind, tornado

thunder: thunderstorm

misc: fog

Append "_night" to let them be used at night.

Options can be changed permanent if stored in .izulu/config.
.SH "AUTHOR"
This manual page was written by Malte Paskuda <malte@paskuda.biz>,
and may be used by others.
