.TH "IZULU" "1" "December 02, 2009" "Malte Paskuda" ""
.SH "NAME"
izulu
.SH "SYNOPSIS"
Set the wallpaper according to the weather

.SH "DESCRIPTION"
This manual page documents briefly the
.B izulu
command.
.PP 
\fBizulu\fP is a tool to change the wallpaper according to the weather. It calls external APIs to detect the weather at the current location.
.SH "OPTIONS"
.TP 
.B \-l "lat:lon"
Set the current position as latitude and longitude coordinates.
.TP 
.BI \-d
Enable daemon\-mode, check the weather every 60 minutes.
.TP 
.BI \-n
Activate night\-mode, different images will be used at night.
.TP 
.BI \-p
Show the forecast in small preview\-icons.
.TP 
.BI \-t 
Show the temperature
.TP 
.TP 
The command to change the wallpaper and the coordinates may be changed in the config ~/.izulu/config.
.SH "FILES"
This script searches for a directory .izulu in the home directory, and relies on the availability of /usr/share/izulu. To override the used images, save them in ~/.izulu with the name gen_sun.jpg, gen_cloud.jpg, gen_rain.jpg, gen_snow.jpg or gen_misc.jpg, which are also the images used if no specific image exists.
To use further distinct images, save them as:

sun: clear.jpg

clouds: partly_cloudy.jpg, cloudy.jpg

rain: rain.jpg, hail.jpg

snow: sleet.jpg, snow.jpg

windy: wind.jpg, tornado.jpg

thunder: thunderstorm.jpg

misc: fog.jpg

Append "_night" to let them be used at night.

.SH "AUTHOR"
This manual page was written by Malte Paskuda <malte@paskuda.biz>,
and may be used by others.
